# You are given two strings s and t. 
# 
#  String t is generated by random shuffling string s and then add one more 
# letter at a random position. 
# 
#  Return the letter that was added to t. 
# 
#  
#  Example 1: 
# 
#  
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
#  
# 
#  Example 2: 
# 
#  
# Input: s = "", t = "y"
# Output: "y"
#  
# 
#  
#  Constraints: 
# 
#  
#  0 <= s.length <= 1000 
#  t.length == s.length + 1 
#  s and t consist of lowercase English letters. 
#  
#  Related Topics Hash Table String Bit Manipulation Sorting 👍 2053 👎 354


# leetcode submit region begin(Prohibit modification and deletion)
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        if not s:
            return t
        freq = [0] * 26
        for c in t:
            index = ord(c) - ord('a')
            freq[index] += 1
        for c in s:
            index = ord(c) - ord('a')
            freq[index] -= 1
        for i, val in enumerate(freq):
            if val:
                return chr(ord('a') + i)
        return ''
# leetcode submit region end(Prohibit modification and deletion)
